# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: circleci/jdk8
    steps:
      - checkout
      - run: javac SortString.java
  # Job two with a unique name
  say_goodbye:
    docker:
      - image: circleci/jdk8
    steps:
      - checkout
      - run: echo "Say goodbye to YAML!"

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye